name: Build a Docker image and Push it to ACR

on:
  push:
    branches:
    - dev 

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
      - name: Set Short Hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Set Docker tag Name
        id: tag
        run: echo "::set-output name=docker_tag::"${GITHUB_REF_NAME/\//"-"}""
 
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./flask-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ steps.tag.outputs.docker_tag }}-${{ steps.vars.outputs.sha_short }}, ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ steps.tag.outputs.docker_tag }}-latest
